experiment:
  name: "wine_score_recipe"
  tracking_uri: "sqlite:///metadata/mlflow/mlruns.db"
  artifact_location: "./metadata/mlflow/mlartifacts"

model_registry:
  model_name: "red_wine_scorer"

INGEST_CONFIG:
  using: "custom"
  location:
    - "http://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv"
    - "http://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-white.csv"
  loader_method: load_file_as_dataframe

INGEST_SCORING_CONFIG:
  using: "custom"
  location:
    - "http://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv"
    - "http://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-white.csv"
  loader_method: load_file_as_dataframe

PREDICT_OUTPUT_CONFIG:
  using: parquet
  location: "./metadata/prediction.parquet"
