recipe: "regression/v1"
target_col: "quality"
primary_metric: "root_mean_squared_error"
steps:
  ingest: {{INGEST_CONFIG}}
  split:
    # ToDo2: specify split ratios for train, validation, and test sets
    split_ratios: [0.8, 0.1, 0.1]
  transform:
    using: custom
    transformer_method: transformer_fn
  train:
    using: custom
    estimator_method: estimator_fn
    # # ToDo9: use the AutoML estimator
    # using: "automl/flaml"
    # time_budget_secs: 60
  evaluate:
    validation_criteria:
      - metric: root_mean_squared_error
        threshold: 1
  register:
    allow_non_validated_model: false
  ingest_scoring: {{INGEST_SCORING_CONFIG}}
  predict:
    output: {{PREDICT_OUTPUT_CONFIG}}

# ToDo5: add custom metrics to our recipe
custom_metrics:
  - name: rounded_root_mean_squared_error
    # Specifies the name of the function in `steps/custom_metrics.py` to use to compute the metric
    function: rounded_root_mean_squared_error
    greater_is_better: False